name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet restore ./src/FamilyMoney/FamilyMoney.csproj
        dotnet pack ./src/FamilyMoney/FamilyMoney.csproj --no-restore
        ls -R
        ls -R | grep "exe"
        gh release create Release ./src/FamilyMoney/bin/Release/net8.0/win-x64/FamilyMoney.exe